'use strict';

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const state={songs:[],playlists:[],view:'all',playlistId:null,query:'',sort:'recent',currentId:null,queue:[],queueIndex:-1,shuffle:false,repeat:0,objectUrl:null};
const audio=$('#audio');

const DB={
  db:null,
  open(){return new Promise((resolve,reject)=>{const req=indexedDB.open('localfy-library',2);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('tracks'))db.createObjectStore('tracks',{keyPath:'id'});};req.onsuccess=()=>{this.db=req.result;resolve()};req.onerror=()=>reject(req.error)})},
  all(){return new Promise((resolve,reject)=>{const r=this.db.transaction('tracks').objectStore('tracks').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})},
  put(value){return new Promise((resolve,reject)=>{const r=this.db.transaction('tracks','readwrite').objectStore('tracks').put(value);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})},
  delete(id){return new Promise((resolve,reject)=>{const r=this.db.transaction('tracks','readwrite').objectStore('tracks').delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
};

function loadSettings(){try{state.playlists=JSON.parse(localStorage.getItem('localfy-playlists'))||[]}catch{state.playlists=[]}audio.volume=Number(localStorage.getItem('localfy-volume')||.85);$('#volume').value=audio.volume}
function savePlaylists(){localStorage.setItem('localfy-playlists',JSON.stringify(state.playlists));window.localfySync?.markPlaylistsDirty()}
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function cleanName(name){return name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim().replace(/\b\w/g,c=>c.toUpperCase())}
function formatTime(sec){if(!Number.isFinite(sec))return '0:00';const m=Math.floor(sec/60),s=Math.floor(sec%60);return `${m}:${String(s).padStart(2,'0')}`}
function formatDate(date){const d=new Date(date);return d.toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:d.getFullYear()===new Date().getFullYear()?undefined:'numeric'}).replace('.','')}
function bytes(n){if(!n)return '0 MB';return `${(n/1048576).toFixed(n>104857600?0:1)} MB`}
function escapeHtml(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function toast(message,type='ok'){const el=document.createElement('div');el.className=`toast ${type==='error'?'error':''}`;el.textContent=message;$('#toastRegion').append(el);setTimeout(()=>el.remove(),3200)}

async function init(){
  loadSettings();
  try{await DB.open();state.songs=await DB.all()}catch(e){console.error(e);state.songs=[];toast('O armazenamento local não pôde ser aberto.','error')}
  bind();render();updateNetwork();registerServiceWorker();
  await window.localfySync?.attach({db:DB,state,render});
}

function bind(){
  $('#importBtn').onclick=openImport;$$('[data-open-import]').forEach(b=>b.onclick=openImport);$('#chooseFilesBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>importFiles([...e.target.files]);
  $('#urlImportBtn').onclick=importUrl;$('#newPlaylistBtn').onclick=()=>{ $('#playlistDialog').showModal();setTimeout(()=>$('#playlistName').focus(),50)}; $('[data-close-playlist]').onclick=()=>$('#playlistDialog').close();
  $('#playlistForm').onsubmit=e=>{e.preventDefault();const name=$('#playlistName').value.trim();if(!name)return;state.playlists.push({id:crypto.randomUUID(),name,trackIds:[]});savePlaylists();$('#playlistName').value='';$('#playlistDialog').close();render();toast('Playlist criada')};
  $('#searchInput').oninput=e=>{state.query=e.target.value.trim().toLowerCase();renderTracks()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderTracks()};
  $$('.nav-item').forEach(b=>b.onclick=()=>selectView(b.dataset.view));$('#mobileMenuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
  $('#playAllBtn').onclick=()=>{const list=filteredSongs();if(list.length)playSong(list[0].id,list.map(s=>s.id))};
  $('#playBtn').onclick=togglePlay;$('#prevBtn').onclick=previous;$('#nextBtn').onclick=next;$('#shuffleBtn').onclick=()=>{state.shuffle=!state.shuffle;$('#shuffleBtn').classList.toggle('active',state.shuffle);toast(state.shuffle?'Modo aleatório ativado':'Modo aleatório desativado')};
  $('#repeatBtn').onclick=()=>{state.repeat=(state.repeat+1)%3;$('#repeatBtn').classList.toggle('active',state.repeat>0);$('#repeatBtn').textContent=state.repeat===2?'↻¹':'↻';toast(['Repetição desativada','Repetir fila','Repetir música'][state.repeat])};
  $('#playerFavorite').onclick=()=>state.currentId&&toggleFavorite(state.currentId);$('#progress').oninput=e=>{if(audio.duration)audio.currentTime=(e.target.value/100)*audio.duration};
  $('#volume').oninput=e=>{audio.volume=Number(e.target.value);localStorage.setItem('localfy-volume',audio.volume)};
  audio.ontimeupdate=()=>{$('#currentTime').textContent=formatTime(audio.currentTime);$('#duration').textContent=formatTime(audio.duration);$('#progress').value=audio.duration?(audio.currentTime/audio.duration)*100:0};
  audio.onplay=()=>{$('#playBtn').textContent='❚❚';renderTracks()};audio.onpause=()=>{$('#playBtn').textContent='▶';renderTracks()};audio.onended=()=>state.repeat===2?(audio.currentTime=0,audio.play()):next();audio.onerror=()=>toast('Não foi possível reproduzir esta faixa.','error');
  window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);document.addEventListener('click',e=>{if(!e.target.closest('.context-menu')&&!e.target.closest('.more-btn'))$('#contextMenu').hidden=true});
}

function selectView(view,playlistId=null){state.view=view;state.playlistId=playlistId;$$('.nav-item,.playlist-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view&&(view!=='playlist'||x.dataset.id===playlistId)));$('.sidebar').classList.remove('open');renderTracks();renderHeading()}
function filteredSongs(){let list=[...state.songs];if(state.view==='favorites')list=list.filter(s=>s.favorite);if(state.view==='recent')list=list.filter(s=>Date.now()-new Date(s.addedAt).getTime()<1000*60*60*24*30);if(state.view==='playlist'){const p=state.playlists.find(p=>p.id===state.playlistId);list=list.filter(s=>p?.trackIds.includes(s.id))}if(state.query)list=list.filter(s=>`${s.title} ${s.artist} ${s.album}`.toLowerCase().includes(state.query));list.sort(state.sort==='title'?(a,b)=>a.title.localeCompare(b.title):state.sort==='artist'?(a,b)=>a.artist.localeCompare(b.artist):((a,b)=>new Date(b.addedAt)-new Date(a.addedAt)));return list}
function render(){renderPlaylistNav();renderTracks();renderHeading();updateStats();updateStorage();updatePlayer()}
function renderHeading(){const map={all:['Todas as músicas','Sua biblioteca particular, disponível mesmo sem internet.'],favorites:['Favoritas','As músicas que você mais gosta.'],recent:['Adicionadas recentemente','Tudo o que chegou à biblioteca nos últimos 30 dias.']};let [title,subtitle]=map[state.view]||['Playlist','Sua seleção personalizada.'];if(state.view==='playlist')title=state.playlists.find(p=>p.id===state.playlistId)?.name||'Playlist';$('#sectionTitle').textContent=title;$('#viewTitle').textContent=state.view==='all'?greeting():title;$('#viewSubtitle').textContent=subtitle}
function greeting(){const h=new Date().getHours();return h<12?'Bom dia':h<18?'Boa tarde':'Boa noite'}
function renderPlaylistNav(){$('#playlistNav').innerHTML=state.playlists.map(p=>`<button class="playlist-item" data-view="playlist" data-id="${p.id}"><span>♫</span>${escapeHtml(p.name)}</button>`).join('');$$('.playlist-item').forEach(b=>b.onclick=()=>selectView('playlist',b.dataset.id));$('#playlistCount').textContent=state.playlists.length}
function renderTracks(){const list=filteredSongs();$('#resultCount').textContent=`${list.length} ${list.length===1?'faixa':'faixas'}`;$('#emptyState').hidden=list.length>0;$('#trackList').innerHTML=list.map((s,i)=>`<div class="track ${state.currentId===s.id?'active':''}" data-id="${s.id}" tabindex="0"><span class="track-index">${state.currentId===s.id&&!audio.paused?'♪':i+1}</span><div class="track-main"><div class="track-cover">${s.cover?`<img src="${s.cover}" alt="" loading="lazy">`:'♫'}</div><div class="track-copy"><span class="track-title">${escapeHtml(s.title)}</span><span class="track-artist">${escapeHtml(s.artist||'Artista desconhecido')}</span></div></div><span class="track-album">${escapeHtml(s.album||'Sem álbum')}</span><span class="track-date">${formatDate(s.addedAt)}</span><button class="heart ${s.favorite?'on':''}" aria-label="Favoritar">${s.favorite?'♥':'♡'}</button><button class="more-btn" aria-label="Mais opções">⋯</button></div>`).join('');
  $$('.track').forEach(row=>{row.ondblclick=()=>playSong(row.dataset.id,list.map(s=>s.id));row.onkeydown=e=>{if(e.key==='Enter')playSong(row.dataset.id,list.map(s=>s.id))};row.querySelector('.track-main').onclick=()=>playSong(row.dataset.id,list.map(s=>s.id));row.querySelector('.track-index').onclick=()=>playSong(row.dataset.id,list.map(s=>s.id));row.querySelector('.heart').onclick=e=>{e.stopPropagation();toggleFavorite(row.dataset.id)};row.querySelector('.more-btn').onclick=e=>{e.stopPropagation();showMenu(e,row.dataset.id)}})
}
function updateStats(){$('#songCount').textContent=state.songs.length;const total=state.songs.reduce((a,s)=>a+(s.duration||0),0);$('#totalDuration').textContent=total?`${Math.round(total/60)} min`:'—'}

async function playSong(id,queue){const song=state.songs.find(s=>s.id===id);if(!song)return;if(state.objectUrl){URL.revokeObjectURL(state.objectUrl);state.objectUrl=null}state.currentId=id;state.queue=queue||filteredSongs().map(s=>s.id);state.queueIndex=state.queue.indexOf(id);audio.src=state.objectUrl=URL.createObjectURL(song.blob);audio.load();try{await audio.play()}catch{toast('Toque novamente para reproduzir.','error')}song.lastPlayed=Date.now();DB.put(song);updatePlayer();renderTracks();updateMediaSession(song)}
function togglePlay(){if(!state.currentId){const list=filteredSongs();if(list.length)playSong(list[0].id,list.map(s=>s.id));return}audio.paused?audio.play():audio.pause()}
function next(){if(!state.queue.length)return;if(state.shuffle)state.queueIndex=Math.floor(Math.random()*state.queue.length);else state.queueIndex++;if(state.queueIndex>=state.queue.length){if(state.repeat===1)state.queueIndex=0;else{state.queueIndex=state.queue.length-1;audio.pause();return}}playSong(state.queue[state.queueIndex],state.queue)}
function previous(){if(audio.currentTime>4){audio.currentTime=0;return}state.queueIndex=Math.max(0,state.queueIndex-1);playSong(state.queue[state.queueIndex],state.queue)}
function updatePlayer(){const s=state.songs.find(s=>s.id===state.currentId);if(!s)return;$('#playerTitle').textContent=s.title;$('#playerArtist').textContent=s.artist||'Artista desconhecido';$('#playerCover').innerHTML=s.cover?`<img src="${s.cover}" alt="">`:'♫';$('#playerFavorite').textContent=s.favorite?'♥':'♡';$('#playerFavorite').classList.toggle('active',s.favorite)}
async function toggleFavorite(id){const s=state.songs.find(s=>s.id===id);if(!s)return;s.favorite=!s.favorite;window.localfySync?.markTrackDirty(s);await DB.put(s);updatePlayer();renderTracks()}

function showMenu(e,id){const song=state.songs.find(s=>s.id===id),menu=$('#contextMenu');menu.innerHTML=`<button data-action="play">▶ Reproduzir agora</button>${state.playlists.map(p=>`<button data-playlist="${p.id}">＋ ${escapeHtml(p.name)}</button>`).join('')}<button data-action="favorite">${song.favorite?'♡ Remover das favoritas':'♥ Adicionar às favoritas'}</button><button class="danger" data-action="delete">Excluir da biblioteca</button>`;menu.hidden=false;menu.style.left=`${Math.min(e.clientX,innerWidth-225)}px`;menu.style.top=`${Math.min(e.clientY,innerHeight-menu.offsetHeight-15)}px`;menu.onclick=async ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.action==='play')playSong(id);if(b.dataset.action==='favorite')toggleFavorite(id);if(b.dataset.playlist)addToPlaylist(id,b.dataset.playlist);if(b.dataset.action==='delete')await deleteSong(id);menu.hidden=true}}
function addToPlaylist(trackId,playlistId){const p=state.playlists.find(p=>p.id===playlistId);if(!p)return;if(!p.trackIds.includes(trackId))p.trackIds.push(trackId);savePlaylists();toast(`Adicionada a “${p.name}”`)}
async function deleteSong(id){const song=state.songs.find(s=>s.id===id);if(!song)return;if(!confirm(`Excluir “${song.title}” de todos os aparelhos sincronizados?`))return;if(state.currentId===id){audio.pause();audio.removeAttribute('src');state.currentId=null}window.localfySync?.queueDelete(song);await DB.delete(id);state.songs=state.songs.filter(s=>s.id!==id);state.playlists.forEach(p=>p.trackIds=p.trackIds.filter(x=>x!==id));savePlaylists();render();toast('Música excluída')}

function openImport(){$('#importDialog').showModal()}
async function importFiles(files){const valid=files.filter(f=>f.type.startsWith('audio/')||f.type.startsWith('video/')||/\.(mp3|mp4|m4a|wav|ogg|flac|aac|webm)$/i.test(f.name));if(!valid.length){toast('Escolha um arquivo de áudio ou vídeo compatível.','error');return}setImporting(true);let count=0;for(const file of valid){try{const meta=await inspectFile(file);const now=new Date().toISOString();const song={id:uid(),title:cleanName(file.name),artist:'Artista desconhecido',album:'Importados',addedAt:now,updatedAt:now,syncState:'pending',favorite:false,duration:meta.duration||0,blob:file,originalName:file.name,size:file.size};await DB.put(song);state.songs.push(song);count++}catch(e){console.error(e)}}setImporting(false);$('#fileInput').value='';$('#importDialog').close();render();toast(`${count} ${count===1?'música importada':'músicas importadas'}`);window.localfySync?.sync()}
function inspectFile(file){return new Promise(resolve=>{const a=document.createElement('audio'),url=URL.createObjectURL(file),done=()=>{URL.revokeObjectURL(url);resolve({duration:Number.isFinite(a.duration)?a.duration:0})};a.preload='metadata';a.onloadedmetadata=done;a.onerror=done;a.src=url;setTimeout(done,4000)})}
async function importUrl(){const raw=$('#urlInput').value.trim();let url;try{url=new URL(raw)}catch{toast('Digite um link válido.','error');return}if(/(youtube\.com|youtu\.be|spotify\.com)/i.test(url.hostname)){toast('Esse serviço não entrega o arquivo de áudio ao PWA. Baixe uma cópia autorizada e importe o arquivo.','error');return}setImporting(true);try{const res=await fetch(url);if(!res.ok)throw new Error();const blob=await res.blob();if(!blob.type.startsWith('audio/')&&!blob.type.startsWith('video/'))throw new Error();const name=decodeURIComponent(url.pathname.split('/').pop()||'Música importada');await importFiles([new File([blob],name,{type:blob.type})]);$('#urlInput').value=''}catch{setImporting(false);toast('O link não permitiu baixar o áudio. Tente importar o arquivo.','error')}}
function setImporting(on){$('#importProgress').hidden=!on;$('#chooseFilesBtn').disabled=on;$('#urlImportBtn').disabled=on}

async function updateStorage(){if(!navigator.storage?.estimate)return;const {usage=0,quota=0}=await navigator.storage.estimate();$('#storageText').textContent=`${bytes(usage)} usados`;$('#storageBar').style.width=`${Math.min(100,usage/quota*100)||0}%`}
function updateNetwork(){$('#offlineBadge').hidden=navigator.onLine;if(navigator.onLine)window.localfySync?.sync()}
function updateMediaSession(song){if(!('mediaSession'in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:song.title,artist:song.artist,album:song.album,artwork:song.cover?[{src:song.cover}]:[]});navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('previoustrack',previous);navigator.mediaSession.setActionHandler('nexttrack',next)}
function registerServiceWorker(){if(!('serviceWorker'in navigator))return;window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('./service-worker.js');registration.update();registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){toast('Nova versão instalada. Atualizando…');worker.postMessage({type:'SKIP_WAITING'})}})});let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()})}catch(error){console.error('Falha ao atualizar o PWA:',error)}})}

init();
